name: intelligent_ambient_beam
version: 0.1.0
publish_to: "none"
description: A Flutter port of the Intelligent Ambient Beam lighting controller app.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
